# 5?
rank.fifth.ranking=5
rank.fifth.money=5000

# 4?
rank.fourth.ranking=4
rank.fourth.money=50000

# 3?
rank.third.ranking=3
rank.third.money=1500000

# 2?
rank.second.ranking=2
rank.second.money=30000000

# 1?
rank.first.ranking=1
rank.first.money=2000000000