# 5?
rank.fifth.count=3
rank.fifth.money=5000

# 4?
rank.fourth.count=4
rank.fourth.money=50000

# 3?
rank.third.count=5
rank.third.money=1500000

# 2?
rank.second.count=5
rank.second.money=30000000

# 1?
rank.first.count=6
rank.first.money=2000000000